on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  run_lint:
    runs-on: ubuntu-latest
    steps:
        run: |
          ruff check src
          ty check src          
